### ISSUE TITLE
Use aws cloudformation package | deploy instead of SAM

### ISSUE THREAD

**Issue by studds** [rewindio/aws-athena-partition-autoloader#1]
Hey, great tool, love it. I use SAM and know it's super useful, however just wanted to let you know that the `aws cloudformation package|deploy` commands work just as well as the equivalent `sam package|deploy` commands, removing the deploy time dependency.

**Comment by dnorth98** [comment]
Thanks for the feedback @studds !  You are correct so I've updated the readme with this info as well.
